### ISSUE TITLE
Argument null Exception

### ISSUE THREAD

**Issue by yuqingyang888** [RWS/Multiselect-ComboBox#100]

**Comment by yuqingyang888** [comment]
Hi,

When I using the MultiSelect ComboBox, an error just occurred. I guess it may have something to do with the single mode.
![screenshot](https://github.com/RWS/Multiselect-ComboBox/assets/36471232/907f9788-2e9b-454c-8cc9-85244c230a76)

**Comment by sdolhaor** [comment]
I couldn't reproduced the issue, but here is an attempt to fix it with some defending programming checks:
https://github.com/RWS/Multiselect-ComboBox/pull/103
