### ISSUE TITLE
When ItemsSource is changed, popup list is not updated

### ISSUE THREAD

**Issue by vaderr12** [RWS/Multiselect-ComboBox#13]
Hi,
When MultiSelectComboBox::ItemsPropertyChangedCallback is executed, it creates new collection view and assign it to ItemsCollectionViewSource. 
The problem is that _dropdownListBox.ItemsSource is not updated and is still pointing to a view created during initialization.

When I've added 
`_dropdownListBox.ItemsSource = ItemsCollectionViewSource?.View;`
 inside ItemsCollectionViewSource set method, popup updates.

**Comment by Impertatore** [comment]
Hi @vaderr12 ,
Can you please provide me with an example (simple project example) of the issue that you are explaining here so that I can understand better if this is an issue we need to review.

If you prefer, send an example to phartnett@sdl.com.

**Comment by sdolhaor** [comment]
This should have been fixed with the most recent version of the package. Can you please check?
