### ISSUE TITLE
Paste text

### ISSUE THREAD

**Issue by BehnamBahmani** [RWS/Multiselect-ComboBox#28]
Hi,

First, I should say the control looks and works great.

I was wondering how we can paste some items? I have tried to implement ApplicationCommands.Paste but it doesn't call/fire the relevant function.

` <sdl:MultiSelectComboBox.CommandBindings>
     <CommandBinding Command="ApplicationCommands.Paste"
              Executed="CommandBinding_Executed"
              CanExecute="CommandBinding_CanExecute" />                                </sdl:MultiSelectComboBox.CommandBindings>`

**Comment by sdolhaor** [comment]
We've added support for pasting items internally: you just need filtering enabled and set the new property EnableBatchSelection = true, then paste items as text, separated by commas or semicolons. More details: see PR #82. Hope it helps!
