### ISSUE TITLE
"ItemsSource" doesn't work correctly

### ISSUE THREAD

**Issue by Vya4ik003** [RWS/Multiselect-ComboBox#39]
When I assigned a value "ItemsSource" my programm stops when i tryed to navigate on page which contains "MultiSelectComboBox".
Thank you in advance! :)

**Comment by Elron1179** [comment]
I have the same problem.

**Comment by Impertatore** [comment]
Hi @Vya4ik003 , @Elron1179, We have released a new version recently 1.0.18 that resolves a threading issue, which seems to be similar to what you guys have reported here.  Can you confirm again with the latest release?

**Comment by mitchcapper** [comment]
wfm with latest release.
