### ISSUE TITLE
Multi Select Text box auto height not working

### ISSUE THREAD

**Issue by ravisoftnweb** [RWS/Multiselect-ComboBox#45]
Hello SDL,

Great work I want to achieve Text box to be Auto height. I tried so many stuff but hard luck can you please help me with the same.

**Comment by sdolhaor** [comment]
Should be resolved by PR #76.
To use auto-height: put the component in a container that allows growing (e.g. Grid with Row Height=Auto) and/or set its VerticalAlignment to Top, Center or Bottom.
