### ISSUE TITLE
Two binding mode is not working for SelectedItems 

### ISSUE THREAD

**Issue by shahshyam** [RWS/Multiselect-ComboBox#51]
Scenario, 
I have custom list of object which is binding with SelectedItems. At some condition, I am removing all items from custom list of object but still getting selected items in combox panel in font end

**Comment by sdolhaor** [comment]
Sorry for the late reply. Can you please check again with the latest update of the component? We have worked a bit in the way SelectedItems work; it should now better support INotifyCollectionChange-based source data (such as ObservableCollections). Thank you in advance for reporting your findings back!

**Comment by mitchcapper** [comment]
can confirm this works.
