### ISSUE TITLE
Component not initialized if datacontext set before

### ISSUE THREAD

**Issue by JeanCollas** [RWS/Multiselect-ComboBox#52]
I have spent half a day trying to understand why I had no elements in my project while the sample works.
The conclusion is that the component is not able to initialize itself if the datacontext is set before the initializecomponents method.
It would be nice to correct that...

**Comment by sdolhaor** [comment]
Sorry for the late answer. Can you please check again with the latest update of the component? We have worked a bit in the initialization areas. Thank you in advance for reporting your findings back!
