### ISSUE TITLE
UpdateAutoCompleteFilterText uses ToString of the item

### ISSUE THREAD

**Issue by JeanCollas** [RWS/Multiselect-ComboBox#53]
`private void UpdateAutoCompleteFilterText(string criteria, object item)` method uses ToString to autocomplete the items.

This would require an autocomplete service to have clean suggestions (and not the type of the classes by default)

**Comment by sdolhaor** [comment]
Should be solved with PR #77. You can now set an IAutoCompleteService object that implements a GetAutoCompleteString method to replace item.ToString().
