### ISSUE TITLE
When IsEditable and EnableFiltering are false the TextBox's caret and MultiSelectComboBox.SelectedItemsPanel.Readonly.Glyph.Template are visible

### ISSUE THREAD

**Issue by caiaandrei** [RWS/Multiselect-ComboBox#68]
When IsEditable and EnableFiltering are false I think the control should act like a normal Combobox.

- Instead of having a TextBox that cannot be used, maybe we can remove it from UI when IsEditable and EnableFiltering are false
- Instead of MultiSelectComboBox.SelectedItemsPanel.Readonly.Glyph.Template it would be nicer to have as dropdown button the MultiSelectComboBox.SelectedItemsPanel.EditMode.Glyph.Template when IsEditable and EnableFiltering are false

**Comment by sdolhaor** [comment]
Addressing this with PR #75
