### ISSUE TITLE
Restore .NET 4.7 compatibility?

### ISSUE THREAD

**Issue by molnarm** [RWS/Multiselect-ComboBox#69]
The solution still builds for .NET 4.7 without problems, would you consider re-adding it to the targets so the NuGet package could be used with older versions?

**Comment by sdolhaor** [comment]
Hello. We would like to use .NET Framework 4.8 for longer term support. However, 4.7.2 can technically be used, indeed, and you can fork the repo if you wish, and adapt it to your project needs, e.g. if you need to still target the previous version of the Framework. Thank you!
