### ISSUE TITLE
Extending this to a Datagrid

### ISSUE THREAD

**Issue by melsawy93** [RWS/Multiselect-ComboBox#79]
Hi, extremely useful combobox that ive been looking for. I am trying to extend this to work with a datagrid but no luck. I have a really simplified project that implements this on a single combobox and it works. However whenever I try to use this in a datatemplate column, it crashes as soon as I select an item from the drop down.
Any hints? Im new to WPF.
[WPFTestApp MultiComboBox.zip](https://github.com/RWS/Multiselect-ComboBox/files/9872322/WPFTestApp.MultiComboBox.zip)

**Comment by melsawy93** [comment]
So I figured out the issue. The internal selecteditems container is of type observablecollection<object>. I didnt expect this to be hard coded especially if you have SelectionMode="Single". Is there any workaround for this? I am binding the selecteditem of the combobox to a single value not an observablecollection.

**Comment by sdolhaor** [comment]
We've added SelectedItem dependency property that internally manages SelectedItems as well, for this purpose (PR #83). Hope it helps.
