### ISSUE TITLE
.net6+Win10 comptiable

### ISSUE THREAD

**Issue by yuqingyang888** [RWS/Multiselect-ComboBox#86]
I use the latest version of MultiSelectComboBox. I'm using Win10 + .Net 6. However, I meet the error of
XamlX.XamlParseException: Unable to resolve type MultiSelectComboBox from namespace http://schemas.sdl.com/xaml 
`<sdl:MultiSelectComboBox Grid.Row="1" Grid.Column="1" Height="40" MinWidth="200"
                                     HorizontalAlignment="Stretch" EnableGrouping="False" />`

Is there anything wrong when I'm using it.

**Comment by sdolhaor** [comment]
I have just tested your example within a new WPF app targeting .NET 6 (on Windows 10), created in Visual Studio 2022 (17.0.3), as you can see in the following screenshot, using the latest version of the Nuget package:

![image](https://user-images.githubusercontent.com/95416895/208375938-58ba3b50-8c13-4aa7-82b9-9d79e01fc787.png)

Apparently, it works runs without any issue. Can you please check that your app project does have a reference to the DLL that contains the component?

**Comment by sdolhaor** [comment]
I will close this issue for now, feel free to reopen it if the issue reproduces in certain conditions (and let us know, of course, the steps to reproduce it; thank you).

**Comment by yuqingyang888** [comment]
I forgot to inform my environments. I am using Avalonia(Win10 + .Net 6) and maybe multiselectcombobox doesn't work with it.
![image](https://user-images.githubusercontent.com/36471232/209607595-f3f92f7d-a64e-4e2f-b064-f6c8c60a6468.png)
