### ISSUE TITLE
Can InputMethod be disabled?

### ISSUE THREAD

**Issue by yuqingyang888** [RWS/Multiselect-ComboBox#87]
I found that the codes
`InputMethod.IsInputMethodEnabled="False"
                                         InputMethod.PreferredImeState="Off"` do not work. Is there any method that could disable the input method?

**Comment by sdolhaor** [comment]
At this time the InputMethod.* properties are let as default on the inner TextBox of the MultiSelectComboBox component.

However, you can use custom templates for MultiSelectComboBox (see our Example app - "Custom control template style" - and inside `MultiSelectComboBox.SelectedItemsPanel.Template`, for the `TextBox x:Name="PART_MultiSelectComboBox_SelectedItemsPanel_Filter_TextBox"`, add appropriate bindings to map the TextBox's InputMethod.* properties to the ones attached to the component instance itself (line 308 of file `MultiSelectComboBox.Example\Styles\MultiSelectComboBox.Custom.ControlTemplate.xaml`):

```
<TextBox x:Name="PART_MultiSelectComboBox_SelectedItemsPanel_Filter_TextBox" IsEnabled="{Binding IsEditMode, RelativeSource={RelativeSource AncestorType=generic:MultiSelectComboBox}}" 
  Focusable="True" IsTabStop="False" Margin="0" ForceCursor="True" BorderThickness="0" BorderBrush="Transparent" Background="Transparent" Padding="1" TextWrapping="NoWrap"
  InputMethod.IsInputMethodEnabled="{Binding Path=(InputMethod.IsInputMethodEnabled), RelativeSource={RelativeSource AncestorType=sdl:MultiSelectComboBox}}"
  InputMethod.PreferredImeState="{Binding Path=(InputMethod.PreferredImeState), RelativeSource={RelativeSource AncestorType=sdl:MultiSelectComboBox}}"/>
```

Please also let us know if this resolves the issue. Thank you in advance!

**Comment by yuqingyang888** [comment]
Thank you for your codes and this issue has been resolved.
