### ISSUE TITLE
Add a SelectedItem Property

### ISSUE THREAD

**Issue by yuqingyang888** [RWS/Multiselect-ComboBox#88]
After using this project for several months, I found that the filtering service works so great that I would like to replace ComboBox with Multiselect-ComboBox in the single select mode. However, the SelectedItems only binds with IList<object>. Could you add a property, SelectedItem, so I could use the single select mode better.

**Comment by sdolhaor** [comment]
Actually there is a SelectedItem property (singular) defined, that properly works IF the developer has set a SelectedItems collection too. To allow developers forget about setting SelectedItems, an idea is just to ensure SelectedItems is initialized to a collection internally, in case it is left null (such as during ApplyTemplate). I've attempted therefore to fix this issue with PR #90.
