### ISSUE TITLE
Wrong bindings of SelectedItems

### ISSUE THREAD

**Issue by yuqingyang888** [RWS/Multiselect-ComboBox#91]
After I updated the sdl.multiselectcombobox to the latest version, I found a strange bug.
`<sdl:MultiSelectComboBox   ItemsSource="{Binding Collections}"
                                             SelectedItems="{Binding SelectedItems}"
                                             SelectionMode="Multiple"/>`

In the ViewModel, I have this codes
`......
SelectedItems = items;...` Initially 'items' has 20 elements. After executing this line, 'SelectedItems' and 'items' only has the first element. While in the UI, there are still has 20 elements. When I use the earlier version, the bug does not exist. Hope you could help me out.

Many thanks!

**Comment by sdolhaor** [comment]
You are right, there was a bug introduced in one of the recent updates. A fix was implemented in PR #92.
