### ISSUE TITLE
Ability to customize item container

### ISSUE THREAD

**Issue by Filipsi** [RWS/Multiselect-ComboBox#93]
Is there a better way to remove rounded corners from selected item container other then overriding entire control template?
Would it be possible to add something like ItemContainerTemplate or ItemContainerStyle so it could be customized easier?

**Comment by sdolhaor** [comment]
I've added a new SelectedItemContainerCornerRadius at MultiSelectComboBox component level - this should help customizing the control without redefining the container's template: PR #94.

**Comment by Filipsi** [comment]
Thank you for a quick response and subsequent pull request.

I have one more thing, regarding item container customization.
When the control is in edit mode, the selected item has a [remove button](https://github.com/RWS/Multiselect-ComboBox/blob/6be58404733c04eb0fdeb3313709df5e0685087e/MultiSelectComboBox/Sdl.MultiSelectComboBox/Themes/Generic/MultiSelectComboBox.xaml#L282) with a "Remove" tool-tip.
I would like to localize this text for my use case, which is currently only possible by overriding entire control template.

**Comment by sdolhaor** [comment]
Thanks for the follow-up. I think we'll need to check if other texts need properties as well, i.e. also in any other places not only on remove button (to avoid the need of templating just for setting their values)...
When I'll have time I'll do some further analysis on it myself. If you, however, have time sooner, you can also try it in a fork and submit a PR with changes; we'll surely review it and merge it if everything is fine!

**Comment by sdolhaor** [comment]
Resolved - https://github.com/RWS/Multiselect-ComboBox/pull/111
Use RemoveToolTipString to localize it

(I verified and there are no other strings to localize)
