### ISSUE TITLE
Suggestion of Add a comparer

### ISSUE THREAD

**Issue by yuqingyang888** [RWS/Multiselect-ComboBox#95]
There are two instances(A & B) of a certain class. These two instances are exact the same, but they have different hash. Is it possible to add a comparer so that if A is selected, then B cannot be added.

**Comment by sdolhaor** [comment]
Can you please be a bit more specific regarding the issue you have? Do you use/bind those object instances (A and B) as selectable items in MultiSelectComboBox control? Maybe you are referring to using IGroupIdentityService (that's where a comparer is needed)? And what do you mean that the objects are the same by have different hash? Generally I think equal objects should have the same hash.

**Comment by yuqingyang888** [comment]
A and B have the same ID(int), an attribute of the class, so in this case, I may regard A and B as the same. If A is selected, B cannot be selected as another item. But I think you are right. equal objects should have the same hash. I should address this problem in my codes.

Another issue is that I cannot get the MultiSelectComboBox's Name, AutomationID, and etc. attributes in the "inspect.exe", even if I set these attribtutes. It may cause some confusion in the application having several multiselect combobox when making UI automation.

**Comment by sdolhaor** [comment]
MultiSelectComboBox is based on custom UI which may be "misunderstood" by inspection software. Maybe you can workaround that issue by using a custom template for the control, and then place the Name, AutomationID on inner elements that you actually want to inspect. Anyway, if you have multiple instances of the control, you should still be able to see the different Name values on the containers of the custom UI they trigger.

Note, regardless, that (according to Microsoft) inspect.exe is considered a legacy tool and it may be unable to "dig in" into the most advanced stuff. Maintained professional inspection tools should have no issue finding the controls.

**Comment by yuqingyang888** [comment]
Thanks so much for your quick response!!!

Could you recommend some professional inspection tools?
